export const playersData = [
  {
    id: '1',
    name: 'Lionel Messi',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p134375751.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/73.png',
    modalPhoto:
      'https://www.psg.fr/media/209026/card-season-22-23-messi.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75',
    age: 36,
    club: 'PSG',
    position: 'RW,ST,CF',
    rating: 98,
    pase: 97,
    shooting: 98,
    passing: 91,
    dribbling: 99,
    defending: 40,
    physical: 77,
    skillMoves: '5/5',
    weakFoot: '4/5',
    foot: 'left',
    attackingWorkRate: 'high',
    country: 'Argentina',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/52.png',
    defensiveWorkRate: 'low',
  },
  {
    id: '2',
    name: 'Cristiano Ronaldo',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p218124609.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/112139.png',
    modalPhoto: 'https://www.pngall.com/wp-content/uploads/11/Profession-Footballer-PNG-File.png',
    age: 38,
    club: 'Al Nassr',
    position: 'ST',
    rating: 99,
    pase: 97,
    shooting: 99,
    passing: 93,
    dribbling: 97,
    defending: 41,
    physical: 88,
    skillMoves: '5/5',
    weakFoot: '5/5',
    foot: 'right',
    attackingWorkRate: 'high',
    country: 'Portugal',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/38.png',
    defensiveWorkRate: 'low',
  },
  {
    id: '3',
    name: 'Karim Benzema',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p151160097.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/243.png',
    modalPhoto:
      'https://www.realmadrid.com/cs/Satellite?blobcol=urldata&blobheader=image%2Fpng&blobkey=id&blobtable=MungoBlobs&blobwhere=1203433215451&ssbinary=true',
    age: 35,
    club: 'Real Madrid',
    position: 'CF',
    rating: 97,
    pase: 93,
    shooting: 96,
    passing: 89,
    dribbling: 93,
    defending: 45,
    physical: 94,
    skillMoves: '4/5',
    weakFoot: '4/5',
    foot: 'right',
    attackingWorkRate: 'high',
    country: 'France',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/18.png',
    defensiveWorkRate: 'medium',
  },
  {
    id: '4',
    name: 'Kylian Mbappe',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p251889987.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/73.png',
    modalPhoto: 'https://www.pngplay.com/wp-content/uploads/13/Mbappe-Background-PNG-Image.png',
    age: 24,
    club: 'PSG',
    position: 'ST',
    rating: 99,
    pase: 99,
    shooting: 98,
    passing: 92,
    dribbling: 99,
    defending: 45,
    physical: 87,
    skillMoves: '5/5',
    weakFoot: '5/5',
    foot: 'right',
    attackingWorkRate: 'high',
    country: 'France',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/18.png',
    defensiveWorkRate: 'low',
  },
  {
    id: '5',
    name: 'Neymar Jr',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p151185815.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/73.png',
    modalPhoto:
      'https://www.psg.fr/media/27051/card-22-23_neymar.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75',
    age: 31,
    club: 'PSG',
    position: 'CAM',
    rating: 99,
    pase: 99,
    shooting: 96,
    passing: 95,
    dribbling: 99,
    defending: 50,
    physical: 78,
    skillMoves: '5/5',
    weakFoot: '5/5',
    foot: 'right',
    attackingWorkRate: 'high',
    country: 'Brasil',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/54.png',
    defensiveWorkRate: 'medium',
  },
  {
    id: '6',
    name: 'Robert Lewandowski',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p184737921.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/241.png',
    modalPhoto: 'https://www.footyrenders.com/render/robert-lewandowski-115.png',
    age: 35,
    club: 'FC Barcelona',
    position: 'ST',
    rating: 99,
    pase: 97,
    shooting: 99,
    passing: 92,
    dribbling: 97,
    defending: 53,
    physical: 99,
    skillMoves: '4/5',
    weakFoot: '5/5',
    foot: 'right',
    attackingWorkRate: 'high',
    country: 'Poland',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/37.png',
    defensiveWorkRate: 'medium',
  },
  {
    id: '7',
    name: 'Kevin De Bruyne',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p251851225.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/10.png',
    modalPhoto: 'https://www.footyrenders.com/render/kevin-de-bruyne-57.png',
    age: 32,
    club: 'Manchester City',
    position: 'CM',
    rating: 99,
    pase: 88,
    shooting: 95,
    passing: 99,
    dribbling: 97,
    defending: 91,
    physical: 99,
    skillMoves: '5/5',
    weakFoot: '5/5',
    foot: 'right',
    attackingWorkRate: 'high',
    country: 'Belgium',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/7.png',
    defensiveWorkRate: 'high',
  },
  {
    id: '8',
    name: 'Erling Haaland',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p201565677.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/10.png',
    modalPhoto: 'https://www.footyrenders.com/render/erling-braut-haland-73.png',
    age: 23,
    club: 'Manchester City',
    position: 'ST',
    rating: 99,
    pase: 99,
    shooting: 99,
    passing: 88,
    dribbling: 94,
    defending: 63,
    physical: 99,
    skillMoves: '5/5',
    weakFoot: '5/5',
    foot: 'right',
    attackingWorkRate: 'high',
    country: 'Norway',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/36.png',
    defensiveWorkRate: 'medium',
  },
  {
    id: '9',
    name: 'Zlatan Ibrahimovic',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/41236.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/47.png',
    modalPhoto:
      'https://www.freeiconspng.com/thumbs/zlatan-ibrahimovic-png/zlatan-ibrahimovic-png-11.png',
    age: 41,
    club: 'Milan',
    position: 'ST',
    rating: 90,
    pase: 90,
    shooting: 91,
    passing: 83,
    dribbling: 87,
    defending: 37,
    physical: 90,
    skillMoves: '4/5',
    weakFoot: '4/5',
    foot: 'right',
    attackingWorkRate: 'medium',
    country: 'Sweden',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/46.png',
    defensiveWorkRate: 'low',
  },
  {
    id: '10',
    name: 'Mesut Ozil',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p100839931.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/101014.png',
    modalPhoto: 'https://www.pngmart.com/files/22/Ozil-Arsenal-PNG-HD.png',
    age: 34,
    club: 'Başakşehir',
    position: 'CAM',
    rating: 93,
    pase: 85,
    shooting: 84,
    passing: 94,
    dribbling: 93,
    defending: 36,
    physical: 77,
    skillMoves: '4/5',
    weakFoot: '4/5',
    foot: 'left',
    attackingWorkRate: 'high',
    country: 'Germany',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/21.png',
    defensiveWorkRate: 'low',
  },
  {
    id: '11',
    name: 'Eden Hazard',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p84069357.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/243.png',
    modalPhoto: 'https://www.pngmart.com/files/22/Eden-Hazard-PNG-Image.png',
    age: 32,
    club: 'Real Madrid',
    position: 'LW',
    rating: 90,
    pase: 91,
    shooting: 87,
    passing: 88,
    dribbling: 93,
    defending: 43,
    physical: 77,
    skillMoves: '4/5',
    weakFoot: '4/5',
    foot: 'right',
    attackingWorkRate: 'medium',
    country: 'Belgium',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/7.png',
    defensiveWorkRate: 'medium',
  },
  {
    id: '12',
    name: 'Mohammed Salah',
    cardPhoto: 'https://www.fifplay.com/img/fifa/23/players/p184758707.png',
    clubPhoto: 'https://www.fifplay.com/img/fifa/23/clubs/9.png',
    modalPhoto: 'https://www.pngmart.com/files/22/Mo-Salah-PNG-Image.png',
    age: 30,
    club: 'Liverpool',
    position: 'RW',
    rating: 96,
    pase: 96,
    shooting: 95,
    passing: 90,
    dribbling: 97,
    defending: 54,
    physical: 83,
    skillMoves: '4/5',
    weakFoot: '3/5',
    foot: 'left',
    attackingWorkRate: 'high',
    country: 'Egypt',
    countryPicture: 'https://www.fifplay.com/img/fifa/23/nations/111.png',
    defensiveWorkRate: 'medium',
  },
];
